### ISSUE TITLE
segfault when trying to delete tag from non-exist m4a file

### ISSUE THREAD

**Issue by Young-Lord** [complexlogic/loudgain#100] opened 2024-02-07 08:25 UTC
I built the program using tar pacckage in `3.4` release on Termux.
```console
/sdcard/Music $ rsgain custom -s d sijdj3.m4a
Segmentation fault
/sdcard/Music $ rsgain custom -s d sijdj3.mp3
[✘] Couldn't write to: sijdj3.mp3
/sdcard/Music $ rsgain custom -s d sijdj3.flac
[✘] Couldn't write to: sijdj3.flac
/sdcard/Music $ rsgain custom -s i sijdj3.flac
[✔] Scanning 'sijdj3.flac'
[✘] Could not open input: No such file or directory
/sdcard/Music $ rsgain custom -s i sijdj3.m4a
[✔] Scanning 'sijdj3.m4a'
[✘] Could not open input: No such file or directory
/sdcard/Music $ rsgain -v
rsgain 3.4 - using:
libebur128     1.2.6
libavformat    60.16.100
libavcodec     60.31.102
libavutil      58.29.100
libswresample  4.12.100
Built with:
TagLib         1.13.1
Compiler:         Clang 17.0.6
Build Date:       2024-02-07
```

**Comment by complexlogic** [comment] 2024-02-08 02:52
Thanks for the report.

I can reproduce this in v3.4. However, this has since been fixed in the `master` branch by https://github.com/complexlogic/rsgain/commit/e3d7da3e34acf16b8266a162729219110b804124. I'm also going to add a check in Custom Mode to immediately fail if the file does not exist, so that the error message is clear to the user.

**Closed as completed by complexlogic** 2024-02-08 02:52 UTC
